### ISSUE TITLE
[Issue]: Armor stand rotation is offset (see photos)

### ISSUE THREAD

**Issue by Karltroid** [Nostalgica-Reverie/Nostalgic-Tweaks#131]
### What is the issue?

Armor stand body or head is slightly rotated, causing models on it to be displayed incorrectly.

### To Reproduce

1. Turn on NT
2. Look at armorstand with a block or item on its head
3. Screenshot
4. Turn off
5. Screenshot
6. See difference

### Minecraft Version

1.21.1

### Modloader

Fabric

### Nostalgic Tweaks Version

v2.0.0-beta.910 

### Log and/or crash report

N/A

### Additional Context

NT ON:
<img width="560" height="480" alt="Image" src="https://github.com/user-attachments/assets/d76373ab-d32f-4277-a7df-af36e39e7f29" />
NT OFF:
<img width="560" height="480" alt="Image" src="https://github.com/user-attachments/assets/f4fafcdd-c67f-4606-951d-d0b9a502cf9a" />

NT ON:
<img width="560" height="480" alt="Image" src="https://github.com/user-attachments/assets/43349fc5-c600-49bd-9d83-792ba04c0b91" />
NT OFF:
<img width="560" height="480" alt="Image" src="https://github.com/user-attachments/assets/3309ab06-7bf3-4ad8-9486-a3652c5d0487" />

### Acknowledgement

- [x] I understand and have fully filled out the form, including the issue name.

**Comment by Adrenix** [comment]
Can you test and see if the latest indev release for beta 9.2 resolves this issue?
https://github.com/Nostalgica-Reverie/Nostalgic-Tweaks/releases/download/2.0.0-beta.920-indev.2/NostalgicTweaks-mc1.21.1-Fabric-2.0.0-beta.920-indev.2.jar

**Comment by Adrenix** [comment]
Potentially fixed in beta 9.2 release. Reopen if not.

**Comment by Karltroid** [comment]
<img width="3440" height="1334" alt="Image" src="https://github.com/user-attachments/assets/e30fd36d-6879-4a08-8d90-3108c762eba4" />

<img width="3440" height="1334" alt="Image" src="https://github.com/user-attachments/assets/a7fb8b2b-6b56-46d2-9dc2-14d6bf72ad3a" />

Did not fix, with NT the model of the item on the armor stand head is still rotated. Unsure if its the entire armor stand, its head, or the model rotating itself

**Comment by Karltroid** [comment]
@Adrenix unable to reopen by the way
